<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="EPRURYAW0942" name="Tests.TestFigures.QuadratTest" tests="6" failures="0" timestamp="2019-12-23T13:55:08 MSK" time="0.006" errors="2">
  <testcase name="checkSquare" time="0.002" classname="Tests.TestFigures.QuadratTest">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
[public void Tests.TestFigures.QuadratTest.checkSquare(java.lang.Double)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: checkSquare([Parameter{index=0, type=java.lang.Double, declaredAnnotations=[]}])
Arguments: [(java.lang.Integer) 10000]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void Tests.TestFigures.QuadratTest.checkSquare(java.lang.Double)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: checkSquare([Parameter{index=0, type=java.lang.Double, declaredAnnotations=[]}])
Arguments: [(java.lang.Integer) 10000]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:43)
at org.testng.internal.Parameters.injectParameters(Parameters.java:925)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:34)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- checkSquare -->
  <testcase name="checkSquare" time="0.001" classname="Tests.TestFigures.QuadratTest"/>
  <testcase name="checkSquare" time="0.000" classname="Tests.TestFigures.QuadratTest"/>
  <testcase name="checkPerimetr" time="0.000" classname="Tests.TestFigures.QuadratTest"/>
  <testcase name="checkPerimetr" time="0.001" classname="Tests.TestFigures.QuadratTest"/>
  <testcase name="checkPerimetr" time="0.002" classname="Tests.TestFigures.QuadratTest">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
[public void Tests.TestFigures.QuadratTest.checkPerimetr(java.lang.Double)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: checkPerimetr([Parameter{index=0, type=java.lang.Double, declaredAnnotations=[]}])
Arguments: [(java.lang.Integer) 10000]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void Tests.TestFigures.QuadratTest.checkPerimetr(java.lang.Double)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: checkPerimetr([Parameter{index=0, type=java.lang.Double, declaredAnnotations=[]}])
Arguments: [(java.lang.Integer) 10000]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:43)
at org.testng.internal.Parameters.injectParameters(Parameters.java:925)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:34)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- checkPerimetr -->
</testsuite> <!-- Tests.TestFigures.QuadratTest -->
